### PR TITLE
Multiple Changes (docker image creation template, MIT license, cookiecutter prompts)

### PR DESCRIPTION
**Pull request by davidbrownell**
- Using new docker image creation functionality in the GitHub Actions workflow template
- Added header to MIT license template
- Provided prompt text for cookiecutter prompts

### CODE REVIEW

**Review by ketanbj — COMMENTED** [review]
LGTM

**Review by jyoung3131 — COMMENTED** [review]
This looks good to me in general. Two questions:

1) Can we point folks to https://choosealicense.com/ as an option for selecting a license?
2) Should the gist creation be optional? My concern would be that folks may not use it or know how to use it without added training.

**Comment by davidbrownell** [comment]
> 1. Can we point folks to https://choosealicense.com/ as an option for selecting a license?

Good idea - I'll make that change.

> 2. Should the gist creation be optional? My concern would be that folks may not use it or know how to use it without added training.

Badges won't display correctly without gist-support. For example, the 2nd badge at https://github.com/gt-sse-center/PythonProjectBootstrapper isn't working due to a gist-permission-related issue that I haven't worked out yet (apparently organizations don't play nice with user accounts). The hope is that the instructions make it easy enough to create a gist, but let me know if they don't seem to be clear enough.

**Review by rfievet — APPROVED** [review]
LGTM

**Pull request merged**
